/*
Enter your query here.
*/
(SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1)
union
(select CITY,length(CITY)
from STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1);
